### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by smooth-baking-powder** [heri16/r8125#4]
Hi,

i tried to install this driver on my Debian Buster. 

I cloned it, went in the folder and use the command ./autorun.sh with root.
```
Check old driver and unload it.
Build the module and install
Makefile:76: /package.mk: No such file or directory
make: *** No rule to make target '/package.mk'.  Stop.
root@c-p001:~/r8125#
```

i tried it in src folder
```
root@c-p001:~/r8125/src# ./autorun.sh

Check old driver and unload it.
Build the module and install
make[1]: *** No rule to make target 'clean'.  Stop.
make: *** [makefile:98: clean] Error 2
```

i dont know how i can fix it.

Best Regards

**Comment by shtefanilie** [comment]
:+1: having the same issue

**Comment by ignaciomosca** [comment]
Same issue

**Comment by ignaciomosca** [comment]
@corincorvus did you managed to solve it?

**Comment by heri16** [comment]
This is a private fork which is meant to be cloned to the Linux source tree and mkconfig to activate building the module. I'll check if I still have the complete documentation on how to use this.

**Comment by ignaciomosca** [comment]
Thanks a lot @heri16

**Comment by heri16** [comment]
Review or cherry-pick this commit to see how this is used to enable the driver on OpenWRT: 

https://github.com/heri16/openwrt/commit/ac713f29744fafbdd9f2ad552f376134624e68e3

Then follow these instructions:
https://openwrt.org/docs/guide-developer/quickstart-build-images
